language: cpp
os: linux
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install -qq qt5-default

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

addons:
  coverity_scan:
    project:
      name: "michalwy/harpoon"
      description: "Build submitted via Travis CI"
    notification_email: michalwy@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan
