language: cpp
os: linux
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - compiler: gcc
      env: GCC_VERSION=5.4
    - compiler: clang
      env: LLVM_VERSION=7

install:
  - sudo apt-get install -qq qt5-default

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi

addons:
  coverity_scan:
    project:
      name: "michalwy/harpoon"
      description: "Build submitted via Travis CI"
    notification_email: michalwy@gmail.com
    build_command_prepend: ""
    build_command:   "make"
    branch_pattern: coverity_scan
